// Auto-generated by scripts/compile-app.ts during `bun run build:binary`.
// In development the backend serves packages/frontend/dist via express.static,
// so this file is intentionally empty — do not add imports here manually.
export const assets: Record<string, any> = {};
