import { readdir, readFile, writeFile, access } from 'fs/promises';
import { join, relative, extname } from 'path';

const ROOT = join(import.meta.dir, '..');
const DIST_DIR = join(ROOT, 'packages/frontend/dist');
const OUT_FILE = join(ROOT, 'packages/backend/src/frontend-assets.ts');

const MIME: Record<string, string> = {
  '.html':  'text/html; charset=utf-8',
  '.js':    'application/javascript; charset=utf-8',
  '.mjs':   'application/javascript; charset=utf-8',
  '.css':   'text/css; charset=utf-8',
  '.json':  'application/json; charset=utf-8',
  '.svg':   'image/svg+xml',
  '.png':   'image/png',
  '.jpg':   'image/jpeg',
  '.jpeg':  'image/jpeg',
  '.webp':  'image/webp',
  '.ico':   'image/x-icon',
  '.woff':  'font/woff',
  '.woff2': 'font/woff2',
  '.ttf':   'font/ttf',
  '.otf':   'font/otf',
  '.eot':   'application/vnd.ms-fontobject',
  '.map':   'application/json',
  '.txt':   'text/plain; charset=utf-8',
};

async function getFiles(dir: string): Promise<string[]> {
  const entries = await readdir(dir, { withFileTypes: true });
  const nested = await Promise.all(
    entries.map((e) => {
      const full = join(dir, e.name);
      return e.isDirectory() ? getFiles(full) : Promise.resolve([full]);
    })
  );
  return nested.flat();
}

async function main() {
  try {
    await access(DIST_DIR);
  } catch {
    console.error(
      '\n[compile-app] ERROR: Frontend dist not found.\n' +
        '  Run "bun run build:frontend" before this script.\n'
    );
    process.exit(1);
  }

  const files = await getFiles(DIST_DIR);
  if (files.length === 0) {
    console.error('[compile-app] ERROR: Frontend dist is empty.');
    process.exit(1);
  }

  let code = '// Auto-generated by scripts/compile-app.ts — do not edit.\n\n';
  code += 'export const assets: Map<string, { data: Buffer; mime: string }> = new Map([\n';

  for (const file of files) {
    const key = '/' + relative(DIST_DIR, file).replace(/\\/g, '/');
    const mime = MIME[extname(file).toLowerCase()] ?? 'application/octet-stream';
    const b64 = (await readFile(file)).toString('base64');
    code += `  [${JSON.stringify(key)}, { data: Buffer.from(${JSON.stringify(b64)}, "base64"), mime: ${JSON.stringify(mime)} }],\n`;
  }

  code += ']);\n';

  await writeFile(OUT_FILE, code, 'utf-8');
  console.log(
    `[compile-app] Embedded ${files.length} frontend assets → packages/backend/src/frontend-assets.ts`
  );
}

main().catch((err) => {
  console.error('[compile-app] Unexpected error:', err);
  process.exit(1);
});
